<?php
namespace app\admin\common;
use think\Controller;
use think\Db;
use think\Session;

/** .-------------------------------------------------------------------
 * |    Software: []
 * | Description:
 * |        Site: www.jechorn.cn
 * |-------------------------------------------------------------------
 * |      Author: 王志传
 * |      Email : <jechorn@163.com>
 * |  CreateTime: 2017/6/10-4:11
 * | Copyright (c) 2016-2019, www.jechorn.cn. All Rights Reserved.
 * '-------------------------------------------------------------------*/
class Base extends Controller
{
    //模块名称
    protected $module_name;
    //控制器名称
    protected  $controller_name;
    //管理员名称
    protected $_adminName;


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $user = Session::get('username');
        $session_id = Session::get('session_id');
        if (empty($user) || empty($session_id)) {
            session('username', null);
            session('session_id', null);
            $this->error('您尚没有登录，请重新登录', url('login/index'));
            exit;
        }
        if (!empty($user) && !empty($session_id)) {
            $where = ['username'=>$user];
            $result = Db::name('admin')->where($where)->find();
            if ($result) {
                if ($result['session_id'] != $session_id) {
                    session('username', null);
                    session('session_id', null);
                    $this->error('你的登录信息过期', url('login/index'));
                    exit;
                }
            } else {
                session('username', null);
                session('session_id', null);
                $this->error('非法登录！', url('login/index'));
                exit;
            }
        }
        $this->_adminName = $user;


    }

    /**
     * 判断是否是ajax提交，不是的话就重新定向
     */
    protected function jump()
    {
        if (!$this->request->isAjax()){
            $module =$this->request->module();
            $this->redirect($module.'/Index/index');

        }
    }




}